;-- XX25 --------------------------------------------------------------------------------------------------------------------------
UBnkProjxLo                 DB  0
UBnkProjxHi                 DB  0
UBnkProjxSgn                DB  0
UBnkProjx                   EQU UBnkProjxLo
UBnkProjyLo                 DB  0
UBnkProjyHi                 DB  0
UBnkProjySgn                DB  0
UBnkProjy                   EQU UBnkProjyLo
UBnkProjzLo                 DB  0
UBnkProjzHi                 DB  0
UBnkProjzSgn                DB  0
UBnkProjz                   EQU UBnkProjzLo
XX25                        EQU UBnkProjxLo
