
membanksize			    equ	$1FFF
    
StartOfBank     	    equ $0000
	
membank0 			    equ $0000
dmaCopySrcAddr		    equ	$0000
membank1 			    equ $2000
membank2 			    equ $4000
membank3 			    equ $6000
membank4 			    equ $8000
membank5 			    equ $a000
membank6 			    equ $c000
ScreenBank              equ $c000
MenuGalChtAddr          equ $c000
MenuEquipSAddr          equ $c000
MenuInventAddr          equ $c000
MenuMarketAddr          equ $c000
DispMarketAddr          equ $c000
MenuShrChtAddr          equ $c000
MenuStatusAddr          equ $c000
MenuSystemAddr          equ $c000
ViewFrontAddr           equ $c000
SunBankAddr             equ $c000
PlanetBankAddr          equ $c000
UniverseBankAddr	    equ $c000
LaunchShipAddr          equ $c000
membank7 			    equ $e000
L1membankAddr   	    equ $e000
L2membankAddr   	    equ $e000
ShipModelsAddr	        equ $e000
SpritemembankAddr       equ $e000
ResetUniverseAddr       equ $e000
StockTableAddr	        equ $e000
CommanderAddr           equ $e000
LAYER2Addr              equ $e000
LAYER1Addr              equ $e000
SPRITEAddr              equ $e000
ConsoleImageAddr        equ $e000
GalaxyDataAddr          equ $e000

EXSDOSMMU0              equ MMU_SLOT_0_REGISTER
EXSDOSMMU1              equ MMU_SLOT_1_REGISTER
DMACpySourceMMU		    equ	MMU_SLOT_0_REGISTER
SunMMU 		            equ MMU_SLOT_6_REGISTER
PlanetMMU 		        equ MMU_SLOT_6_REGISTER
UniverseMMU 		    equ MMU_SLOT_6_REGISTER
ScreenBankMMU           equ MMU_SLOT_6_REGISTER
MenuEquipSMMU           equ MMU_SLOT_6_REGISTER
MenuShrChtMMU           equ MMU_SLOT_6_REGISTER
MenuGalChtMMU           equ MMU_SLOT_6_REGISTER
MenuInventMMU           equ MMU_SLOT_6_REGISTER
MenuSystemMMU           equ MMU_SLOT_6_REGISTER
MenuMarketMMU           equ MMU_SLOT_6_REGISTER
DispMarketMMU           equ MMU_SLOT_6_REGISTER
MenuStatusMMU           equ MMU_SLOT_6_REGISTER
LaunchShipMMU           equ MMU_SLOT_6_REGISTER
L1memMMU       		    equ MMU_SLOT_7_REGISTER
L2memMMU       		    equ MMU_SLOT_7_REGISTER
SpritememMMU   		    equ MMU_SLOT_7_REGISTER
ShipModelMMU  		    equ MMU_SLOT_7_REGISTER
ResetUniverseMMU	    equ MMU_SLOT_7_REGISTER
CommanderMMU	        equ MMU_SLOT_7_REGISTER
StockTableMMU		    equ MMU_SLOT_7_REGISTER
ConsoleImageDataMMU	    equ MMU_SLOT_7_REGISTER
GalaxyDataMMU	        equ MMU_SLOT_7_REGISTER
 
BankResetUniv           equ 49
BankMenuShrCht          equ 50
BankMenuGalCht          equ 51
BankMenuInvent          equ 52
BankMenuSystem          equ 53
BankMenuMarket          equ 54
BankStockTable          equ 55
BankCommander           equ 56
BankLAYER2              equ 57
BankLAYER1              equ 58
BankShipModels1         equ 59
BankSPRITE              equ 60
BankConsole             equ 61
BankFrontView           equ 62
BankMenuStatus          equ 63
BankMenuEquipS          equ 64
BankLaunchShip          equ 65
BankDispMarket          equ 66
BankShipModels2         equ 67
BankShipModels3         equ 68
BankShipModels4         equ 69

BankUNIVDATA0           equ 70
BankUNIVDATA1           equ 71
BankUNIVDATA2           equ 72
BankUNIVDATA3           equ 73
BankUNIVDATA4           equ 74
BankUNIVDATA5           equ 75
BankUNIVDATA6           equ 76
BankUNIVDATA7           equ 77
BankUNIVDATA8           equ 78
BankUNIVDATA9           equ 79
BankUNIVDATA10          equ 80
BankUNIVDATA11          equ 81
BankUNIVDATA12          equ 82
BankSunData             equ 83
BankPlanetData          equ 84
 
BankGalaxyData0         equ 91
BankGalaxyData1         equ 92
BankGalaxyData2         equ 93
BankGalaxyData3         equ 94
BankGalaxyData4         equ 95
BankGalaxyData5         equ 96
BankGalaxyData6         equ 97
BankGalaxyData7         equ 98

BankROM                 equ 255
