IO_LAYER2_PORT                          EQU $123B
IO_EXT_BANK_PORT 			            EQU $DFFD ; 57341
IO_BANK_PORT                            EQU $7FFD ; 32765
REGISTER_NUMBER_PORT					EQU $243B
REGISTER_VALUE_PORT						EQU $253B
SPRITE_SLOT_PORT						EQU $303B
SPRITE_INFO_PORT                        EQU $0057
SPRITE_PATTERN_UPLOAD_PORT				EQU $005B

MACHINE_ID_REGISTER						EQU 0
VERSION_REGISTER						EQU 1
RESET_REGISTER		    				EQU 2
MACHINE_TYPE_REGISTER					EQU 3
PAGE_RAM_REGISTER						EQU 4
PERIPHERAL_1_REGISTER					EQU 5
PERIPHERAL_2_REGISTER					EQU 6
TURBO_MODE_REGISTER						EQU 7
PERIPHERAL_3_REGISTER					EQU 8
ANTI_BRICK_SYSTEM_REGISTER				EQU 10
LAYER2_RAM_PAGE_REGISTER				EQU 18
LAYER2_RAM_SHADOW_REGISTER      		EQU 19
TRANSPARENCY_COLOUR_REGISTER			EQU 20
SPRITE_LAYERS_SYSTEM_REGISTER			EQU 21
LAYER2_OFFSET_X_REGISTER				EQU 22
LAYER2_OFFSET_Y_REGISTER				EQU 23
CLIP_WINDOW_LAYER2_REGISTER				EQU 24
CLIP_WINDOW_SPRITES_REGISTER			EQU 25
CLIP_WINDOW_ULA_REGISTER				EQU 26
CLIP_WINDOW_CONTROL_REGISTER			EQU 28
ACTIVE_VIDEO_LINE_MSB_REGISTER			EQU 30
ACTIVE_VIDEO_LINE_LSB_REGISTER			EQU 31
LINE_INTERRUPT_CONTROL_REGISTER			EQU 34
LINE_INTERRUPT_VALUE_LSB_REGISTER		EQU 35
KEYMAP_HIGH_ADDRESS_REGISTER			EQU 40
KEYMAP_LOW_ADDRESS_REGISTER				EQU 41
KEYMAP_HIGH_DATA_REGISTER				EQU 42
KEYMAP_LOW_DATA_REGISTER				EQU 43
DAC_B_MIRROR_REGISTER                   EQU 44
DAC_AB_MIRROR_REGISTER                  EQU 45
DAC_C_MORROR_REGISTER                   EQU 46
TILEMAP_OFFSET_XMSB_REGISTER            EQU 47
TILEMAP_OFFSET_XLSB_REGISTER            EQU 48
TILEMAP_OFFSET_YMSB_REGISTER            EQU 49
LORES_OFFSET_X_REGISTER					EQU 50
LORES_OFFSET_Y_REGISTER					EQU 51
SPRITE_PORT_INDEX_REGISTER              EQU 52
SPRITE_PORT_ATTR0_REGISTER              EQU 53
SPRITE_PORT_ATTR1_REGISTER              EQU 54
SPRITE_PORT_ATTR2_REGISTER              EQU 55
SPRITE_PORT_ATTR3_REGISTER              EQU 56
SPRITE_PORT_ATTR4_REGISTER              EQU 57
PALETTE_INDEX_REGISTER					EQU 64
PALETTE_VALUE_8BIT_REGISTER				EQU 65
PALETTE_FORMAT_REGISTER					EQU 66
PALETTE_CONTROL_REGISTER				EQU 67
PALETTE_VALUE_9BIT_REGISTER				EQU 68
MMU_SLOT_0_REGISTER						EQU 80
MMU_SLOT_1_REGISTER						EQU 81
MMU_SLOT_2_REGISTER						EQU 82
MMU_SLOT_3_REGISTER						EQU 83
MMU_SLOT_4_REGISTER						EQU 84
MMU_SLOT_5_REGISTER						EQU 85
MMU_SLOT_6_REGISTER						EQU 86
MMU_SLOT_7_REGISTER						EQU 87
COPPER_DATA_REGISTER					EQU 96
COPPER_CONTROL_LOW_REGISTER				EQU 97
COPPER_CONTROL_HIGH_REGISTER			EQU 98
DISPLAY_CONTROL_1_REGISTER              EQU 105
LAYER_2_CONTROL_REGISTER                EQU 112
LAYER_2_X_OFFSET_MSB_REGISTER           EQU 113
DEBUG_LEDS_REGISTER						EQU 255


GetNextReg:	MACRO register
            push bc
                ld bc,$243B
                    ld a,register
                    out (c),a
                    inc b
                in a,(c)
            pop bc
            ENDM
