;-- XX25 --------------------------------------------------------------------------------------------------------------------------
SBnKProjxLo                 DB  0
SBnKProjxHi                 DB  0
SBnKProjxSgn                DB  0
SBnKProjx                   EQU SBnKProjxLo
SBnKProjyLo                 DB  0
SBnKProjyHi                 DB  0
SBnKProjySgn                DB  0
SBnKProjy                   EQU SBnKProjyLo
SBnKProjzLo                 DB  0
SBnKProjzHi                 DB  0
SBnKProjzSgn                DB  0
SBnKProjz                   EQU SBnKProjzLo
SXX25                       EQU SBnKProjxLo
