AntiLogTable:	        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 1
                        db 2
                        db 2
                        db 2
                        db 2
                        db 2
                        db 2
                        db 2
                        db 2
                        db 2
                        db 2
                        db 2
                        db 2
                        db 2
                        db 2
                        db 2
                        db 2
                        db 2
                        db 2
                        db 2
                        db 3
                        db 3
                        db 3
                        db 3
                        db 3
                        db 3
                        db 3
                        db 3
                        db 3
                        db 3
                        db 3
                        db 3
                        db 3
                        db 4
                        db 4
                        db 4
                        db 4
                        db 4
                        db 4
                        db 4
                        db 4
                        db 4
                        db 4
                        db 4
                        db 5
                        db 5
                        db 5
                        db 5
                        db 5
                        db 5
                        db 5
                        db 5
                        db 6
                        db 6
                        db 6
                        db 6
                        db 6
                        db 6
                        db 6
                        db 7
                        db 7
                        db 7
                        db 7
                        db 7
                        db 7
                        db 8
                        db 8
                        db 8
                        db 8
                        db 8
                        db 8
                        db 9
                        db 9
                        db 9
                        db 9
                        db 9
                        db 10
                        db 10
                        db 10
                        db 10
                        db 11
                        db 11
                        db 11
                        db 11
                        db 12
                        db 12
                        db 12
                        db 12
                        db 13
                        db 13
                        db 13
                        db 14
                        db 14
                        db 14
                        db 14
                        db 15
                        db 15
                        db 16
                        db 16
                        db 16
                        db 17
                        db 17
                        db 17
                        db 18
                        db 18
                        db 19
                        db 19
                        db 19
                        db 20
                        db 20
                        db 21
                        db 21
                        db 22
                        db 22
                        db 23
                        db 23
                        db 24
                        db 24
                        db 25
                        db 25
                        db 26
                        db 26
                        db 27
                        db 28
                        db 28
                        db 29
                        db 29
                        db 30
                        db 31
                        db 32
                        db 32
                        db 33
                        db 34
                        db 34
                        db 35
                        db 36
                        db 37
                        db 38
                        db 38
                        db 39
                        db 40
                        db 41
                        db 42
                        db 43
                        db 44
                        db 45
                        db 46
                        db 47
                        db 48
                        db 49
                        db 50
                        db 51
                        db 52
                        db 53
                        db 54
                        db 56
                        db 57
                        db 58
                        db 59
                        db 61
                        db 62
                        db 64
                        db 65
                        db 66
                        db 68
                        db 69
                        db 71
                        db 72
                        db 74
                        db 76
                        db 77
                        db 79
                        db 81
                        db 82
                        db 84
                        db 86
                        db 88
                        db 90
                        db 92
                        db 94
                        db 96
                        db 98
                        db 100
                        db 103
                        db 105
                        db 107
                        db 109
                        db 112
                        db 114
                        db 117
                        db 119
                        db 122
                        db 125
                        db 128
                        db 130
                        db 133
                        db 136
                        db 139
                        db 142
                        db 145
                        db 148
                        db 152
                        db 155
                        db 158
                        db 162
                        db 165
                        db 169
                        db 173
                        db 177
                        db 181
                        db 184
                        db 189
                        db 193
                        db 197
                        db 201
                        db 206
                        db 210
                        db 215
                        db 219
                        db 224
                        db 229
                        db 234
                        db 239
                        db 245
